In [3]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import GradientBoostingRegressor, BaggingRegressor

from sklearn.metrics import mean_squared_error, r2_score

In [4]:
#Loading dataset
#Training dataset_sales
sales = pd.read_csv("sales.csv")

In [5]:
#Exploring dataset
sales.head()

,True_index,Store_ID,Day_of_week,Date,Nb_customers_on_day,Open,Promotion,State_holiday,School_holiday,Sales
0,0,625,3,2013-11-06,641,1,1,0,0,7293
1,1,293,2,2013-07-16,877,1,1,0,1,7060
2,2,39,4,2014-01-23,561,1,1,0,0,4565
3,3,676,4,2013-09-26,1584,1,1,0,0,6380
4,4,709,3,2014-01-22,1477,1,1,0,0,11647

In [6]:
sales.tail()

,True_index,Store_ID,Day_of_week,Date,Nb_customers_on_day,Open,Promotion,State_holiday,School_holiday,Sales
640835,712040,674,6,2014-09-20,611,1,0,0,0,4702
640836,712041,1014,4,2015-01-15,1267,1,1,0,0,12545
640837,712042,135,6,2015-06-20,595,1,0,0,0,5823
640838,712043,810,1,2014-08-18,599,1,1,0,1,7986
640839,712044,592,1,2013-03-18,798,1,1,0,0,6565

In [7]:
sales.shape

(640840, 10)

In [8]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640840 entries, 0 to 640839
Data columns (total 10 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   True_index           640840 non-null  int64
 1   Store_ID             640840 non-null  int64
 2   Day_of_week          640840 non-null  int64
 3   Date                 640840 non-null  object
 4   Nb_customers_on_day  640840 non-null  int64
 5   Open                 640840 non-null  int64
 6   Promotion            640840 non-null  int64
 7   State_holiday        640840 non-null  object
 8   School_holiday       640840 non-null  int64
 9   Sales                640840 non-null  int64
dtypes: int64(8), object(2)
memory usage: 48.9+ MB

In [9]:
sales.describe()

,True_index,Store_ID,Day_of_week,Nb_customers_on_day,Open,Promotion,School_holiday,Sales
count,640840.000000,640840.000000,640840.000000,640840.000000,640840.000000,640840.000000,640840.000000,640840.000000
mean,355990.675084,558.211348,4.000189,633.398577,0.830185,0.381718,0.178472,5777.469011
std,205536.290268,321.878521,1.996478,464.094416,0.375470,0.485808,0.382910,3851.338083
min,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,178075.750000,280.000000,2.000000,405.000000,1.000000,0.000000,0.000000,3731.000000
50%,355948.500000,558.000000,4.000000,609.000000,1.000000,0.000000,0.000000,5746.000000
75%,533959.250000,837.000000,6.000000,838.000000,1.000000,1.000000,0.000000,7860.000000
max,712044.000000,1115.000000,7.000000,5458.000000,1.000000,1.000000,1.000000,41551.000000

In [10]:
#data cleaning
#check missing values
#check duplicate rows
sales.isnull().sum()

True_index             0
Store_ID               0
Day_of_week            0
Date                   0
Nb_customers_on_day    0
Open                   0
Promotion              0
State_holiday          0
School_holiday         0
Sales                  0
dtype: int64

In [11]:
sales.duplicated().sum()

0

In [12]:
#feature Engg
#converting the date
sales["Date"] = pd.to_datetime(sales["Date"])

In [13]:
sales["Year"] = sales["Date"].dt.year
sales["Month"] = sales["Date"].dt.month
sales["Day"] = sales["Date"].dt.day
sales["Week"] = sales["Date"].dt.isocalendar().week.astype(int)

In [14]:
sales.drop("Date", axis=1, inplace=True)

In [15]:
sales.head()

,True_index,Store_ID,Day_of_week,Nb_customers_on_day,Open,Promotion,State_holiday,School_holiday,Sales,Year,Month,Day,Week
0,0,625,3,641,1,1,0,0,7293,2013,11,6,45
1,1,293,2,877,1,1,0,1,7060,2013,7,16,29
2,2,39,4,561,1,1,0,0,4565,2014,1,23,4
3,3,676,4,1584,1,1,0,0,6380,2013,9,26,39
4,4,709,3,1477,1,1,0,0,11647,2014,1,22,4

In [16]:
#seperating Features and target
X = sales.drop("Sales", axis=1)

y = sales["Sales"]

In [17]:
#Identify the categorical Feature
categorical_features = ["State_holiday"]

In [18]:
#One-Hot Encoding
preprocessor = ColumnTransformer(
    transformers=[
        (
            "holiday",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        )
    ],
    remainder="passthrough"
)

In [19]:
#Spliting dataset(Test,train)
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [20]:
#Creating model Pipelines
#Linear regression(Training)
linear_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LinearRegression())
])

In [21]:
linear_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('holiday',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['State_holiday'])])),
                ('model', LinearRegression())])

In [22]:
#Decision Tree(Training)
tree_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", DecisionTreeRegressor(random_state=42))
])

In [23]:
tree_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('holiday',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['State_holiday'])])),
                ('model', DecisionTreeRegressor(random_state=42))])

In [24]:
#Linear Regression(Evaluating)
linear_predictions = linear_pipeline.predict(X_test)

mse_linear = mean_squared_error(y_test, linear_predictions)
rmse_linear = np.sqrt(mse_linear)
r2_linear = r2_score(y_test, linear_predictions)

print("Linear Regression")
print("MSE :", mse_linear)
print("RMSE:", rmse_linear)
print("R² :", r2_linear)

Linear Regression
MSE : 2195737.508757088
RMSE: 1481.8021152492286
R² : 0.8541524290278215

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_base.py:280: RuntimeWarning: divide by zero encountered in matmul
  return X @ coef_ + self.intercept_
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_base.py:280: RuntimeWarning: overflow encountered in matmul
  return X @ coef_ + self.intercept_
/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_base.py:280: RuntimeWarning: invalid value encountered in matmul
  return X @ coef_ + self.intercept_

In [25]:
#decision Tree(Evaluating)
tree_predictions = tree_pipeline.predict(X_test)

mse_tree = mean_squared_error(y_test, tree_predictions)
rmse_tree = np.sqrt(mse_tree)
r2_tree = r2_score(y_test, tree_predictions)

print("Decision Tree")
print("MSE :", mse_tree)
print("RMSE:", rmse_tree)
print("R² :", r2_tree)

Decision Tree
MSE : 1670389.1159337745
RMSE: 1292.4353430380083
R² : 0.8890476688740405

 # RandomForestRegressor

In [26]:

from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline

# Random Forest (Training)
rf_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1))
])

rf_pipeline.fit(X_train, y_train)

# Random Forest (Evaluating)
rf_predictions = rf_pipeline.predict(X_test)

mse_rf = mean_squared_error(y_test, rf_predictions)
rmse_rf = np.sqrt(mse_rf)
r2_rf = r2_score(y_test, rf_predictions)

print("Random Forest")
print("MSE :", mse_rf)
print("RMSE:", rmse_rf)
print("R² :", r2_rf)

Random Forest
MSE : 833638.9880718736
RMSE: 913.0383278219341
R² : 0.9446271601258881

In [27]:
results = pd.DataFrame({
    "Model": ["Linear Regression", "Decision Tree", "Random Forest"],
    "RMSE": [rmse_linear, rmse_tree, rmse_rf],
    "R2": [r2_linear, r2_tree, r2_rf]
})
print(results)

               Model         RMSE        R2
0  Linear Regression  1481.802115  0.854152
1      Decision Tree  1292.435343  0.889048
2      Random Forest   913.038328  0.944627